translation_dict = {
    'aa': ('ays','ᔑᔑ'),
    'bb': ('bas','ʖʖ'),
    'cc': ('cas','ᓵᓵ'),
    'dd': ('das',''),
    'ee': ('eas',''),
    'ff': ('fas',''),
    'gg': ('get',''),
    'hh': ('ha',''),
    'ii': ('ey',''),
    'jj': ('ya',''),
    'kk': ('ka',''),
    'll': ('la',''),
    'nn': ('na',''),
    'oo': ('ohu',''),
    'pp': ('pa',''),
    'qq': ('que',''),
    'rr': ('re',''),
    'ss': ('su',''),
    'tt': ('za',''),
    'uu': ('ue',''),
    'vv': ('ve',''),
    'ww': ('we',''),
    'xx': ('xe',''),
    'yy': ('ye',''),
    'zz': ('da',''),
    'a': ('ay',"ᔑ"),
    'b': ('bs',"ʖ"),
    'c': ('see',"ᓵ"),
    'd': ('du',"⟍̅"),
    'e': ('eh',"ᒷ"),
    'f': ('fr',"⎓"),
    'g': ('ge',"˧"),
    'h': ('hn',"⍑"),
    'i': ('ie',"¦"),
    'j': ('ya',"⋮"),
    'k': ('har',"ꖌ"),
    'l': ('leh',"ꖎ"),
    'm': ('meh',"ᒲ"),
    'n': ('ne',"リ"),
    'o': ('ohe',"𝙹"),
    'p': ('pu',"!¡"),
    'q': ('cue',"ᑑ"),
    'r': ('rue',"∷"),
    's': ('see',"ᓭ"),
    't': ('tra',"ℸ"),
    'u': ('we',"⚍"),
    'v': ('va',"⍊"),
    'w': ('vik',"∴"),
    'x': ('xsh',"/"),
    'y': ('vi',"ǁ"),
    'z': ('cha',"⨅"),
     'any': ('any-we','ᔑリǁ'),
     'at': ('a-tra',),
     'anyway': ('an-vick-ahwe',),
     'ability': ('aysab-vitra',),
    'are': ('',''),
    'able': ('vik',''),
    'absoloutley': ('abys-oh-letra',''),
    'aquire': ('ar-patra',''),
    'buy': ('see-whe',''),
    'bat': ('sab-tra',''),
    'back': ('sal-char',''),
    'ball': ('sa-lar',''),
    'base': ('say-char',''),
    'big': ('be-sige',''),
    'call': ('say-lah',''),
    'carry': ('say-rah-leh',''),
    'cheap': ('sena-chapu',''),
    'card': ('see-rodue',''),
    'capacity': ('setra-ve',''),
    'code': ('so-sune',''),
    'cold': ('seo-lune',''),
    'click': ('sele-sar',''),
    'child': ('sene-lehdo',''),
    'client': ('seleh-hentra',''),
    'daily': ('do-whaleh',''),
    'damage': ('dure-gamy',''),
    'miata': ('mia-tra','0-0'),
    'exc': ('sab',''),
    'ca': ('say',''),
    'ch': ('sena',''),
    'da': ('Dowh',''),
    'da': ('dure',''),
    'ehx': ('Hex',''),
    'exp': ('ha',''),
    'bso': ('scoh',''),
    'lehehwhie': ('letra',''),
    'lehoh': ('loneh',''),
    'psw': ('Hex',''),
    'tra': ('tre-na',''),
    'nsl': ('sey',''),
    'ato': ('rue',''),
    'aff': ('afas',''),
    'tho': ('tran ',''),
    'tha': ('tran',''),
    'ayleho': ('alee',''),
    'staff': ('see-tra-afas',''),
    'lat': ('letra',''),
    'thi': ('tra-ien',''),
    'ngs': ('neh-la',''),
    'ing': ('ie-neh',''),
    'is': ('i-se',''),
    'lik': ('le-hara',''),
    'to': ('tra-ohe',''),
    'wha': ('vik-eneh',''),
    'whe': ('vik-enay',''),
     'ㅁ': ('ay',"ᔑ"),
'ㅠ': ('bs',"ʖ"),
'ㅊ': ('see',"ᓵ"),
'ㅇ': ('du',"⟍̅"),
'ㄷ': ('eh',"ᒷ"),
'ㄹ': ('fr',"⎓"),
'ㅎ': ('ge',"˧"),
'ㅗ': ('hn',"⍑"),
'ㅑ': ('ie',"¦"),
'ㅓ': ('ya',"⋮"),
'ㅏ': ('har',"ꖌ"),
'ㅣ': ('leh',"ꖎ"),
'ㅡ': ('meh',"ᒲ"),
'ㅜ': ('ne',"リ"),
'ㅐ': ('ohe',"𝙹"),
'ㅔ': ('pu',"!¡"),
'ㅂ': ('cue',"ᑑ"),
'ㄱ': ('rue',"∷"),
'ㄴ': ('see',"ᓭ"),
'ㅅ': ('tra',"ℸ"),
'ㅕ': ('we',"⚍"),
'ㅍ': ('va',"⍊"),
'ㅈ': ('vik',"∴"),
'ㅌ': ('xsh',"/"),
'ㅛ': ('vi',"ǁ"),
'ㅋ': ('cha',"⨅"),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),
    # 'ehx': ('Hex',''),

    'ehx': ('Hex','')
}